let a, b, c;
a = 5;
b = 2;
c = a + b;
document.getElementById("demo").innerHTML = "Summa on " + c;
c = a - b;
document.getElementById("demo2").innerHTML = "Erotus on " + c;
c = a * b;
document.getElementById("demo3").innerHTML = "Tulo on " + c;
c = a / b;
document.getElementById("demo4").innerHTML = "Jakolasku on " + c;
c = a % b;
document.getElementById("demo5").innerHTML = "Jakojäännös on " + c;
a --;
b ++;
document.getElementById("demo6").innerHTML = "A on " + a;
document.getElementById("demo7").innerHTML = "B on " + b;
d = a**b;
document.getElementById("demo8").innerHTML = "Potenssi on " + d;